sudo: required
services:
  - docker

before_install:
  - docker build -t my_image -f Dockerfile.dev .

script:
  - docker run my_image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockertwo"
  env: "Dockertwo-env"
  bucket_name: "elasticbeanstalk-us-east-2-880534901276"
  bucket_path: "dockertwo"

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
